# Generated by Django 5.1 on 2024-09-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={'verbose_name_plural': 'Contact queries'},
        ),
    ]
