# Generated by Django 5.1 on 2024-09-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
